path sheynsw

diff --git a/.github/workflows/prerelease.yml b/.github/workflows/prerelease.yml
--- a/.github/workflows/prerelease.yml
+++ b/.github/workflows/prerelease.yml
@@ -1,19 +1,18 @@
-name: Prerelease
+name: Prerelease build
 on:
-  workflow_dispatch:
   push:
+    branches:
+      - Alpha
     paths-ignore:
+      - '**.md'
+      - '.github/**'
       - "docs/**"
       - "README.md"
+      - '!.github/workflows/prerelease.yml'
+  pull_request:
     branches:
       - Alpha
-      - Beta
-  pull_request_target:
-    branches:
-      - Alpha
-      - Beta
-env:
-  REGISTRY: docker.io
+
 jobs:
   Build:
     permissions: write-all
@@ -22,58 +21,46 @@ jobs:
       fail-fast: false
       matrix:
         job:
-          - {
-              type: "WithoutCGO",
-              target: "linux-amd64 linux-amd64-compatible",
-              id: "1",
-            }
-          - {
-              type: "WithoutCGO",
-              target: "linux-armv5 linux-armv6 linux-armv7",
-              id: "2",
-            }
-          - {
-              type: "WithoutCGO",
-              target: "linux-arm64 linux-mips64 linux-mips64le",
-              id: "3",
-            }
-          - {
-              type: "WithoutCGO",
-              target: "linux-mips-softfloat linux-mips-hardfloat linux-mipsle-softfloat linux-mipsle-hardfloat",
-              id: "4",
-            }
-          - {
-              type: "WithoutCGO",
-              target: "freebsd-386 freebsd-amd64 freebsd-arm64",
-              id: "5",
-            }
-          - {
-              type: "WithoutCGO",
-              target: "windows-amd64-compatible windows-amd64 windows-386",
-              id: "6",
-            }
-          - {
-              type: "WithoutCGO",
-              target: "windows-arm64 windows-arm32v7",
-              id: "7",
-            }
-          - {
-              type: "WithoutCGO",
-              target: "darwin-amd64 darwin-arm64 android-arm64",
-              id: "8",
-            }
-          - { type: "WithCGO", target: "windows/*", id: "1" }
-          - { type: "WithCGO", target: "linux/386", id: "2" }
-          - { type: "WithCGO", target: "linux/amd64", id: "3" }
-          - { type: "WithCGO", target: "linux/arm64,linux/riscv64", id: "4" }
-          - { type: "WithCGO", target: "linux/arm,", id: "5" }
-          - { type: "WithCGO", target: "linux/arm-6,linux/arm-7", id: "6" }
-          - { type: "WithCGO", target: "linux/mips,linux/mipsle", id: "7" }
-          - { type: "WithCGO", target: "linux/mips64", id: "8" }
-          - { type: "WithCGO", target: "linux/mips64le", id: "9" }
-          - { type: "WithCGO", target: "darwin-10.16/*", id: "10" }
-          - { type: "WithCGO", target: "android", id: "11" }
-
+          - { type: "WithoutCGO", target: "linux-amd64", id: "1" }
+          - { type: "WithoutCGO", target: "linux-amd64-compatible", id: "2" }
+          - { type: "WithoutCGO", target: "linux-armv5", id: "3" }
+          - { type: "WithoutCGO", target: "linux-armv6", id: "4" }
+          - { type: "WithoutCGO", target: "linux-armv7", id: "5" }
+          - { type: "WithoutCGO", target: "linux-arm64", id: "6" }
+          - { type: "WithoutCGO", target: "linux-mips64", id: "7" }
+          - { type: "WithoutCGO", target: "linux-mips64le", id: "8" }
+          - { type: "WithoutCGO", target: "linux-mipsle-hardfloat", id: "9" }
+          - { type: "WithoutCGO", target: "linux-mipsle-softfloat", id: "10" }
+          - { type: "WithoutCGO", target: "linux-mips-hardfloat ", id: "11" }
+          - { type: "WithoutCGO", target: "linux-mips-softfloat", id: "12" }
+          # - {
+              # type: "WithoutCGO",
+              # target: "freebsd-386 freebsd-amd64 freebsd-arm64",
+              # id: "5",
+            # }
+          - { type: "WithoutCGO", target: "windows-amd64-compatible", id: "13" }
+          - { type: "WithoutCGO", target: "windows-amd64", id: "14" }
+          - { type: "WithoutCGO", target: "windows-386", id: "15" }
+          - { type: "WithoutCGO", target: "windows-arm64", id: "16" }
+          - { type: "WithoutCGO", target: "windows-arm32v7", id: "17" }
+          - { type: "WithoutCGO", target: "android-arm64", id: "18" }
+          # - {
+              # type: "WithoutCGO",
+              # target: "darwin-amd64 darwin-arm64 android-arm64",
+              # id: "8",
+            # }
+          # - { type: "WithCGO", target: "windows/*", id: "1" }
+          # - { type: "WithCGO", target: "linux/386,linux/amd64", id: "2" }
+          # - { type: "WithCGO", target: "linux/arm64,linux/riscv64", id: "3" }
+          # - {
+              # type: "WithCGO",
+              # target: "linux/arm,linux/arm-6,linux/arm-7",
+              # id: "4",
+            # }
+          # - { type: "WithCGO", target: "linux/mips,linux/mipsle", id: "5" }
+          # - { type: "WithCGO", target: "linux/mips64,linux/mips64le", id: "6" }
+          # - { type: "WithCGO", target: "darwin-10.16/*", id: "7" }
+          - { type: "WithCGO", target: "android", id: "1" }
     steps:
       - name: Check out code into the Go module directory
         uses: actions/checkout@v3
@@ -87,10 +74,10 @@ jobs:
         run: echo "VERSION=alpha-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
         shell: bash
 
-      - name: Set variables
-        if: ${{github.ref_name=='Beta'}}
-        run: echo "VERSION=beta-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
-        shell: bash
+      # - name: Set variables
+        # if: ${{github.ref_name=='Beta'}}
+        # run: echo "VERSION=beta-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
+        # shell: bash
 
       - name: Set variables
         if: ${{github.ref_name==''}}
@@ -102,7 +89,7 @@ jobs:
           echo "NAME=clash.meta" >> $GITHUB_ENV
           echo "REPO=${{ github.repository }}" >> $GITHUB_ENV
           echo "ShortSHA=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV
-          echo "BUILDTIME=$(date -u)" >> $GITHUB_ENV
+          echo "BUILDTIME=$(TZ=Asia/Jakarta date)" >> $GITHUB_ENV
         shell: bash
 
       - name: Set ENV
@@ -117,10 +104,10 @@ jobs:
           go-version: "1.20"
           check-latest: true
 
-      - name: Test
-        if: ${{ github.ref_name=='Beta' && matrix.job.id=='1' && matrix.job.type=='WithoutCGO' }}
-        run: |
-          go test ./...
+      # - name: Test
+        # if: ${{ github.ref_name=='Beta' && matrix.job.id=='1' && matrix.job.type=='WithoutCGO' }}
+        # run: |
+          # go test ./...
 
       - name: Build WithoutCGO
         if: ${{ matrix.job.type=='WithoutCGO' }}
@@ -143,8 +130,11 @@ jobs:
           ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
         run: |
           mkdir bin
-          CC=${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android33-clang
-          CGO_ENABLED=1 CC=${CC} GOARCH=arm64 GOOS=android go build -tags ${TAGS} -trimpath -ldflags "${LDFLAGS}" -o bin/${NAME}-android-arm64
+          CC=${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin
+          CGO_ENABLED=1 CC=${CC}/aarch64-linux-android33-clang GOARCH=arm64 GOOS=android go build -tags ${TAGS} -trimpath -ldflags "${LDFLAGS}" -o bin/${NAME}-android-arm64
+          CGO_ENABLED=1 CC=${CC}/armv7a-linux-androideabi33-clang GOARCH=arm GOOS=android GOARM=7 go build -tags ${TAGS} -trimpath -ldflags "${LDFLAGS}" -o bin/${NAME}-android-armv7
+          # CGO_ENABLED=1 CC=${CC}/i686-linux-android33-clang GOARCH=386 GOOS=android go build -tags ${TAGS} -trimpath -ldflags "${LDFLAGS}" -o bin/${NAME}-android-x86
+          # CGO_ENABLED=1 CC=${CC}/x86_64-linux-android33-clang GOARCH=amd64 GOOS=android go build -tags ${TAGS} -trimpath -ldflags "${LDFLAGS}" -o bin/${NAME}-android-x64
 
       - name: Set up xgo
         if: ${{ matrix.job.type=='WithCGO' && matrix.job.target!='android' }}
@@ -226,10 +216,13 @@ jobs:
           files: bin/*
           prerelease: true
           generate_release_notes: true
+
   Docker:
     permissions: write-all
     needs: [Build]
     runs-on: ubuntu-latest
+    if: ${{ startsWith(github.event.head_commit.message, '[docker]') }}
+
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
@@ -287,3 +280,46 @@ jobs:
             linux/arm64/v8
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
+
+  # telegram:
+    # name: telegram Upload Release
+    # runs-on: ubuntu-latest
+    # needs: Upload
+    # steps:
+      # - name: Donwload Artifacts
+        # uses: actions/download-artifact@v3
+        # with:
+          # name: artifact
+          # path: artifacts
+      # - name: Release
+        # run: |
+          # mkdir upload
+          # find artifacts -name "*.gz" -exec cp {} upload \;
+          # find artifacts -name "*.zip" -exec cp {} upload \;
+          
+          # function upload() {
+            # for gz in $@; do
+              # echo ">> Uploading $gz"
+              # curl https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendDocument \
+                # -X POST \
+                # -F chat_id="${{ secrets.TELEGRAM_CHANNEL }}" \
+                # -F document="@$gz" \
+                # --silent --show-error --fail >/dev/null &
+            # done
+            # for job in $(jobs -p); do
+              # wait $job || exit 1
+            # done
+          # }
+          # upload upload/*
+
+  del_runs:
+    runs-on: ubuntu-latest
+    needs: Upload
+    steps:
+      - name: Delete workflow runs
+        uses: Mattraks/delete-workflow-runs@v2
+        with:
+          token: ${{ github.token }}
+          repository: ${{ github.repository }}
+          retain_days: 0
+          keep_minimum_runs: 0
